version: '3'
services:
  whoami:
    image: "traefik/whoami"
    labels:
      - traefik.enable=true
      - traefik.http.services.my-whoami.loadbalancer.server.port=80
      # - traefik.http.services.whoami.loadbalancer.passHostHeader=true
      # - traefik.http.routers.my-whoami_http.rule=Path(`/whoami`)
      # - traefik.http.routers.my-whoami_http.service=my-whoami
      # - traefik.http.routers.my-whoami_http.entrypoints=http
      # - traefik.http.routers.my-whoami_http.middlewares=my-plugin
      # - traefik.http.routers.whoami_https.rule=Host(`whoami.${DOMAIN}`) ||  (Host(`${DOMAIN}`, `www.${DOMAIN}`) && Path(`/whoami`))
      # - traefik.http.routers.whoami_https.service=whoami
      # - traefik.http.routers.whoami_https.entrypoints=web_secure
      # # - traefik.http.routers.whoami_https.middlewares=traefik-real-ip@file
      # - traefik.http.routers.whoami_https.tls=true
      # - traefik.http.routers.whoami_https.tls.options=intermediate@file
    networks:
      - traefik
networks:
  traefik:
    external:
      name: frontend