version: '3'
services:
  traefik:
    image: traefik:v2.6.1
    restart: always
    ports:
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml
      - ./config/traefik:/etc/traefik/config:ro
      - /home/paxos/go:/plugins-local
networks:
    default:
        external:
            name: frontend